// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkrvvlfhdjxqadmupldb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrcnZ2bGZoZGp4cWFkbXVwbGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5Mzg1NjgsImV4cCI6MjA1MTUxNDU2OH0.qBq-sPlsEGBDgXfoWts9ecZy0esUodHwQ6VWf_0AiKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);